name: real-code
version: '1.0.0'
summary: Краткое описание вашего приложения
description: |
  Полное описание вашего приложения.
grade: stable
confinement: strict
base: core24

parts:
  my-app:
    plugin: python
    source: .
    python-requirements:
      - requirements.txt
    stage-packages:
      - python3-tk
      - libcairo2
      - libglib2.0-0

apps:
  real-code:
    command: bin/real-code-bin
    extensions: [gnome]
    # Направляем Python к системным пакетам Tkinter внутри snap
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$SNAP/lib/python3.12/site-packages
    plugs:
      - network
      - home

